### ISSUE TITLE
[FEATURE] Implement fill in the stack layout's childs

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#36]

**Comment by rene-kt** [comment]
![image](https://user-images.githubusercontent.com/49681380/161045464-4d76fa1f-de0d-4b57-b894-48ad0882848b.png)

This issue is mainly happening due to the property called `width: double.infinity` that should expand the widget as most as possible. I tried to wrap the widget in a `Expanded()` but it produces the same output @brunoamuniz @kaiquemancoso 

Unfortunately, i will have to change a whole of code (specially about the way that we're build the widget in the template just to support this property). I would like to have it a look from @pedrohcbrl just to see if i'm not missing anything

**Comment by brunoamuniz** [comment]
Fill worked but it introduced another bug... it is not getting the right properties for the button (color, size, etc)

<img width="885" alt="Screen Shot 2022-04-04 at 10 20 00" src="https://user-images.githubusercontent.com/3296036/161552755-62747051-53c5-45e6-b559-08c39d3946aa.png">

**Comment by rene-kt** [comment]
@brunoamuniz i will put this issue for testing again, because i made some changes in the alignment: 

- Some layouts will working only in mobile resolutions, lets take this an example (the wide button is setted as `fill`: 
![image](https://user-images.githubusercontent.com/49681380/161637546-0c0664e9-9088-479a-b6f7-ccf75746311a.png)

![image](https://user-images.githubusercontent.com/49681380/161637667-7b8023fa-dd09-49b1-84d3-0831e5c60eec.png)

> If you start putting fill often, the layout should be responsive (needs testing)

the alignment its a little bit different but it produces the same output.

___ 

And about the different colors for buttons, its covered in the issue #71

**Comment by brunoamuniz** [comment]
something strange is happening, I am using fill, fill in both axis

<img width="786" alt="Screen Shot 2022-04-05 at 09 38 18" src="https://user-images.githubusercontent.com/3296036/161755288-84ea80be-c953-4588-82bd-a08c4742d675.png">

[project.zip](https://github.com/Flutter-Vision/FlutterVision/files/8418160/project.zip)

https://www.figma.com/file/SF15TM62dQGrUVZEzTNZwU/Untitled?node-id=1%3A2

**Comment by brunoamuniz** [comment]
in this other example it is not using properly the Fill property and also showing one exception
<img width="1390" alt="Screen Shot 2022-04-05 at 09 47 31" src="https://user-images.githubusercontent.com/3296036/161757006-2048d32a-6900-49f4-b6e5-068f9893e7c9.png">
[project.zip](https://github.com/Flutter-Vision/FlutterVision/files/8418217/project.zip)
